### ISSUE TITLE
Allow SSH connections from host

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/softnet#6]
So that the Cirrus CLI's `persistent_worker:` isolation with `tart:` would work.

Originally discussed in https://github.com/cirruslabs/tart/discussions/178.

**Comment by fkorotkov** [comment]
@saracen PTAL at softnet `0.2.0`. I've removed the discussion in https://github.com/cirruslabs/tart since it was a bug and the is no way to convert a discussion into an issue. 😅
